# Generated by Django 4.2 on 2023-05-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_rename_image_post_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_cat',
            field=models.ImageField(default='category/default_img.jpg', upload_to='category/'),
        ),
    ]
