# Generated by Django 4.2 on 2023-05-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_category_image_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_author',
            field=models.CharField(default='Admin', max_length=100),
        ),
    ]
