# Generated by Django 4.2 on 2023-05-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_rename_cat_created_at_post_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
