# Generated by Django 4.2 on 2023-05-26 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_category_cat_created_at_post_post_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
