# Generated by Django 4.2 on 2023-05-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
